### PR TITLE
Fix decoding map

### LINKED ISSUE #287: error decoding map: key is not a valid map index
I tried this:

```kotlin
val d = mapOf("key" to "value")
val t = Toml.encodeToString(d)

Toml.decodeFromString<Map<String,String>>(t)
```
It throws an `IllegalArgumentException: key is not a valid map index`.

This seems so simple that maybe I'm using it wrong?

It works fine with `Json` serialization.

### PR DESCRIPTION
**Pull request by BOOMeranGG**
Fixes #287

### CODE REVIEW

File: ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMapDecoder.kt [hunk 1]
```diff
@@ -99,4 +126,21 @@ public class TomlMapDecoder(
...
     }
+
+    public companion object {
+        /**
+         * @param deserializer - deserializer provided by Kotlin compiler
+         * @param rootNode - root node for decoding (created after parsing)
+         * @param config - decoding configuration for parsing and serialization
+         * @return decoded (deserialized) object of type T
+         */
+        public fun <T> decode(
```
Comment (orchestr7) [inline ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMapDecoder.kt:137]: So what was the problem? You have introduced a new decoder?

Comment (BOOMeranGG) [reply ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMapDecoder.kt:137]: Example from test `testNestedRootMapDecoder`, we have this toml:
```
my_key_1 = "my_value_1"
my_key_2 = "my_value_2"
```

And we got Exception `my_key_1 is not a valid map index` in TomlMainDecoder::decodeElementIndex. **rootNode** has 2 TomlKeyValuePrimitive but no TomlTable (ofc, we can't know it on parsing level and anyway we don't have TomlTable.name)

In that case we can:
- Use `TomlMapDecoder.decode()` instead of `TomlMainDecoder.decode()` in `Toml` class after parsing if we have descriptor.kind == StructureKind.MAP
- Do the same in `TomlMainDecoder`
- ? smth else

I decided to make the first option just because it's easier :)

Comment (orchestr7) [reply ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMapDecoder.kt:137]: Yeah, sounds very reasonable, LGTM!

**Review by orchestr7 — APPROVED** [review]

File: ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMapDecoder.kt (hunk 1 above)
Comment (BOOMeranGG) [reply ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMapDecoder.kt:137]: I don't have strong opinion so far, how do you think we can avoid TomlMainDecoder?
