### PR TITLE
Extend custom serializers support in decoding

### LINKED ISSUE #127: Add the support for custom serialization
```
class CustomSerializerTest {
    object ColorAsStringSerializer : KSerializer<Color> {
        override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("Color", PrimitiveKind.STRING)

        override fun serialize(encoder: Encoder, value: Color) {
            TODO()
        }

        override fun deserialize(decoder: Decoder): Color {
            val value = decoder.decodeString()
            return Color(value.toLong())
        }
    }

    @Serializable(with = ColorAsStringSerializer::class)
    data class Color(val rgb: Long)

    @Serializable
    data class Settings(val background: Color, val foreground: Color)

    @Test
    fun testDecodingWithCustomSerializer() {
        println(Toml.decodeFromString<Settings>(
            """
                [background]
                    rgb = 0
                [foreground]
                    rgb = 0
            """.trimIndent()
        ))
    }
}
```

will cause 

```
This kind of node should not be processed in TomlDecoder.decodeValue(): [background]
com.akuleshov7.ktoml.exceptions.InternalDecodingException: This kind of node should not be processed in TomlDecoder.decodeValue(): [background]
	at app//com.akuleshov7.ktoml.decoders.TomlMainDecoder.decodeKeyValue$ktoml_core(TomlMainDecoder.kt:84)
	at app//com.akuleshov7.ktoml.decoders.TomlAbstractDecoder.decodeString(TomlAbstractDecoder.kt:101)
	at app//com.akuleshov7.ktoml.decoders.CustomSerializerTest$ColorAsStringSerializer.deserialize(CustomSerializerTest.kt:23)
	at app//com.akuleshov7.ktoml.decoders.CustomSerializerTest$ColorAsStringSerializer.deserialize(CustomSerializerTest.kt:15)
	at app//kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260)
	at app//kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
```

### PR DESCRIPTION
**Pull request by BOOMeranGG**
Fix #127 

Added tests from https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#custom-serializers

Contextual (#282) isn't implemented yet

### CODE REVIEW

File: ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlArrayDecoder.kt [hunk 1]
```diff
@@ -99,4 +99,21 @@ public class TomlArrayDecoder(
...
     override fun decodeNotNullMark(): Boolean = currentPrimitiveElementOfArray !is TomlNull
+
+    public companion object {
+        /**
+         * @param deserializer - deserializer provided by Kotlin compiler
+         * @param tomlKeyValueArray - TomlKeyValueArray node for decoding
+         * @param config - decoding configuration for parsing and serialization
+         * @return decoded (deserialized) object of type T
+         */
+        public fun <T> decode(
```
Comment (orchestr7) [inline ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlArrayDecoder.kt:110]: hm, don't get the idea - why this should be added to particular desrializers like ArrayDecoder?

File: ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/custom/CustomSerializerTest.kt [hunk 2]
```diff
@@ -0,0 +1,335 @@
...
+import kotlinx.serialization.decodeFromString
+import kotlinx.serialization.descriptors.*
+import kotlinx.serialization.encoding.CompositeDecoder
+import kotlinx.serialization.encoding.Decoder
+import kotlinx.serialization.encoding.Encoder
+import kotlinx.serialization.encoding.decodeStructure
+import kotlin.test.Test
+import kotlin.test.assertEquals
+
+class CustomSerializerTest {
```
Comment (orchestr7) [inline ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/custom/CustomSerializerTest.kt:17]: I remember, I had `CustomSerializerTest` with some @Ignored tests

kotlin/com/akuleshov7/ktoml/decoders/CustomSerializerTest.kt

May be unify and remove @Ignored in some of tests? 🙏🏾

**Comment by orchestr7** [comment]
Generally LGTM, also conflicts might be resolved

**Comment by orchestr7** [comment]
I believe that once we merge it, it'll be time to make the release. @BOOMeranGG, this release will be yours—and only yours—and it will be officially named 'Evgeny Bykov's Release'! :)

I'll also write up a post on Reddit. It’s finally time to push through that 500-star milestone )

**Comment by BOOMeranGG** [comment]
> I believe that once we merge it, it'll be time to make the release. @BOOMeranGG, this release will be yours—and only yours—and it will be officially named 'Evgeny Bykov's Release'! :)
> 
> I'll also write up a post on Reddit. It’s finally time to push through that 500-star milestone )

Haha, thank you! But don't forget other contributors, all my commits were based on it :)

File: ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/custom/CustomSerializerTest.kt (hunk 2 above)
Comment (BOOMeranGG) [reply ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/custom/CustomSerializerTest.kt:17]: It's the same class, I just moved it to */custom/* directory

File: ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlArrayDecoder.kt (hunk 1 above)
Comment (BOOMeranGG) [reply ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlArrayDecoder.kt:110]: I did the same as I did for map: https://github.com/orchestr7/ktoml/pull/291#discussion_r1988002032
Now in Toml.kt we have:

```kotlin
    private fun <T> decode(deserializer: DeserializationStrategy<T>, parsedToml: TomlFile): T =
        when (deserializer.descriptor.kind) {
            StructureKind.LIST -> TomlArrayDecoder.decode(deserializer, parsedToml.getFirstChild() as TomlKeyValueArray, inputConfig)
            StructureKind.MAP -> TomlMapDecoder.decode(deserializer, parsedToml, inputConfig)
            else -> TomlMainDecoder.decode(deserializer, parsedToml, inputConfig)
        }

```

Comment (orchestr7) [reply ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlArrayDecoder.kt:110]: got it!

**Review by orchestr7 — APPROVED** [review]
