### PR TITLE
Fix quoted and dotted keys

### LINKED ISSUE #235: Support for quoted keys and values with special symbols
`String.validateSymbols()` in `ktoml-core-jvm:0.5.0` performs an extra `trimQuotes()`, which prevents assignment to quoted keys containing special symbols.

For example, consider the following line of valid (per [language docs](https://github.com/toml-lang/toml/blob/main/toml.md#keys)) TOML:

```
"androidx.activity:activity-compose" = {}
```

This yields the following exception:

```
ParseException: <...>: Not able to parse the key: ["androidx.activity:activity-compose"] as it contains invalid symbols.
```

### PR DESCRIPTION
**Pull request by BOOMeranGG**
Fixes #235

- Removed extra `trimQuotes()` in `String.validateSymbols()` to allow special symbols in quoted keys #235

- Added `trimSingleQuotes()` in `TomlKey.last()` to fix [this](https://github.com/orchestr7/ktoml/issues/235#issuecomment-2081630668) 

- Renamed `String.getCommentStartIndex` to `String.indexOfFirstOutsideQuotes` and extended it's usage to search for any symbol, which allows to use '=' in quoted keys

- Added extra `.trim()` in `String.splitKeyToTokens` to fit the following requirements:
  image

### CODE REVIEW

File: ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/pairs/keys/TomlKey.kt [hunk 1]
```diff
@@ -49,7 +50,10 @@ public class TomlKey internal constructor(
      * Gets the last key part, with all whitespace and quotes trimmed, i.e. `c` in
      * `a.b.' c '`
      */
-    public fun last(): String = keyParts.last().trimQuotes().trim()
+    public fun last(): String = keyParts.last()
+        .trimQuotes()
+        .trimSingleQuotes()
```
Comment (orchestr7) [inline ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/pairs/keys/TomlKey.kt:55]: May be merge methods with `trimQuotes` if it is possible?

**Review by orchestr7 — APPROVED** [review]
